---
=====>config.yaml
--- !ruby/object:OpenStruct
table:
  :telegram_bot: 
  :chat_id: 
  :target_per_trade: 
  :exit_per_trade: 
  :target_per_day:
  :bigcandle_target_per_trade: 
  :bigcandle_exit_per_trade: 
  :bigcandle_target_per_day: 
  :260105:
    :big_candle_size: 
    :strike_ce: 
    :instrument_ce: 
    :strike_pe: 
    :instrument_pe: 
    :quantity:
  :256265:
    :big_candle_size: 
    :strike_ce: 
    :instrument_ce: 
    :strike_pe: 
    :instrument_pe: 
    :quantity: 

====>levels.yaml
---
levels:
 - 50000
 - 24814
 - 24435
 - 0

all_levels:
 - 50000
 - 32652
 - 32604
 - 32555
 - 32501

====>login.yaml
---
- client1: 
  :api_key: 
  :api_secret: 
  :client: 
  :login_url: 
  :otp: 
  :password: 
  :request_token: 
  :access_token: 
  :login_time: 
- client2: 
  :api_key: 
  :api_secret: 
  :client: 
  :login_url:
  :otp: 
  :password: 
  :request_token: 
  :access_token: 
  :login_time: 
