---
- client1: 
  :api_key: 7mv1fm34t9w7jxqy
  :api_secret: bcmlycn98i7c6yjhqmiplanym2uys03e
  :client: ZC6151
  :login_url: https://kite.zerodha.com/connect/login?api_key=7mv1fm34t9w7jxqy
  :otp: 123456
  :password: asd@1234
  :request_token: RC4COXj5sjgL1k18VvSf47S4IPPH44qx
  :access_token: XYFD7xTbROs2HXRQo4eq55i76iXqJo3n
  :login_time: '2020-10-20 09:00:10'
- client2: 
  :api_key: f0sp6y6y9yey7okf
  :api_secret: jyz4h6hil96jgyhkoudlk2gvb69gcmcm
  :client: XI0687
  :login_url: https://kite.zerodha.com/connect/login?api_key=f0sp6y6y9yey7okf
  :otp: 123456
  :password: asd@1234
  :request_token: IoO5QfEiojgQDZqW3n8w19VdA0k1RIMW
  :access_token: Vs0cW6Q84dq7SeBxBWygWsgVu3f2BBwo
  :login_time: '2020-10-20 09:00:15'
